# Generated by Django 4.0.1 on 2022-02-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_auth_management', '0002_messagevalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagevalues',
            name='artist',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='messagevalues',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
    ]
